apiVersion: v1
kind: Pod
metadata:
  name: bad-startup-timeout
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    startupProbe:
      httpGet:
        path: /startup
        port: 8080
      timeoutSeconds: 30
      periodSeconds: 10
