apiVersion: v1
kind: Pod
metadata:
  name: good-pod-ephemeral
spec:
  containers:
  - name: main-container
    image: nginx:latest
  ephemeralContainers:
  - name: ephemeral-container
    image: busybox:latest
    securityContext:
      privileged: false
