apiVersion: v1
kind: Pod
metadata:
  name: good-pod-initcontainer
spec:
  initContainers:
  - name: init-container
    image: busybox:latest
    securityContext:
      privileged: false
  containers:
  - name: main-container
    image: nginx:latest
