apiVersion: v1
kind: Pod
metadata:
  name: good-ai-workload
  labels:
    ai.workload/type: model-serving
    networkpolicy.networking.k8s.io/policy-group: ai-inference
spec:
  hostNetwork: false
  containers:
  - name: inference-server
    image: pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime
