apiVersion: v1
kind: Pod
metadata:
  name: bad-pod-default-01
spec:
  serviceAccountName: default
  containers:
  - name: nginx
    image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: bad-pod-default-02
spec:
  serviceAccountName: default
  containers:
  - name: app
    image: busybox:latest
    command: ["sh", "-c", "sleep 3600"]
