# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  creationTimestamp: null
  name: forbid-cpu-limits
spec:
  # disable templating because it can cause issues with ValidatingPolicy
  template: false
  steps:
  - name: step-01
    try:
    - apply:
        file: ../forbid-cpu-limits.yaml
    - assert:
        resource:
          apiVersion: policies.kyverno.io/v1
          kind: ValidatingPolicy
          metadata:
            name: forbid-cpu-limits
          spec:
            validationActions:
            - Deny
    - assert:
        file: policy-ready.yaml
    - sleep: 
       duration: 10s
  - name: step-02
    try:
    - apply:
        file: pods-good.yaml
    - apply:
        expect:
        - check:
            (contains($error, 'Containers may not define CPU limits.')): true
        file: pods-bad.yaml
    - apply:
        file: podcontrollers-good.yaml
    - apply:
        expect:
        - check:
            (contains($error, 'Containers may not define CPU limits.')): true
        file: podcontrollers-bad.yaml

  - name: updates
    try:
    - patch:
        resource:
          apiVersion: v1
          kind: Pod
          metadata:
            name: good01
            labels:
              admission-update: allowed
    - assert:
        resource:
          apiVersion: v1
          kind: Pod
          metadata:
            name: good01
            labels:
              admission-update: allowed
    - patch:
        resource:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: gooddeployment01
          spec:
            template:
              spec:
                containers:
                - name: busybox
                  image: ghcr.io/kyverno/test-busybox:1.35
                  resources:
                    limits:
                      cpu: 500m
        expect:
        - check:
            (contains($error, 'Containers may not define CPU limits.')): true
    - assert:
        resource:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: gooddeployment01
          spec:
            template:
              spec:
                containers:
                - name: busybox
                  image: ghcr.io/kyverno/test-busybox:1.35
                  (contains(keys(resources.limits || `{}`), 'cpu')): false
