apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-good-release-tag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nginx:1.27.0
