apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-bad-snapshot-tag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: registry.example.com/team/web:2.0.0-SNAPSHOT@sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
