apiVersion: policies.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: block-updates-deletes
status:
  conditionStatus:
    (conditions[?type == 'RBACPermissionsGranted']):
    - message: Background scanning disabled; reporting permissions not required.
      reason: Succeeded
      status: "True"
    (conditions[?type == 'WebhookConfigured']):
    - message: Webhook configured.
      reason: Succeeded
      status: "True"
      type: WebhookConfigured
 