apiVersion: v1
kind: Pod
metadata:
  name: bad-pod-initcontainer
spec:
  initContainers:
  - name: init-container
    image: busybox:latest
    securityContext:
      allowPrivilegeEscalation: true
  containers:
  - name: main-container
    image: nginx:latest
