apiVersion: policies.kyverno.io/v1alpha1
kind: MutatingPolicy
metadata:
  name: add-volume
  namespace: kyverno
  annotations:
    policies.kyverno.io/title: Add Volume to Deployment
    policies.kyverno.io/category: Sample
    policies.kyverno.io/subject: Deployment, Volume
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Some Kubernetes applications like HashiCorp Vault must perform some modifications
      to resources in order to invoke their specific functionality. Often times, that functionality
      is controlled by the presence of a label or specific annotation. This policy, based on HashiCorp
      Vault, adds a volume and volumeMount to a Deployment if there is an annotation called
      "vault.k8s.corp.net/inject=enabled" present.
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments"]
  matchConditions:
    - name: "Has vault inject annotation"
      expression: "object.spec.template.metadata.annotations.exists(a, a == 'vault.k8s.corp.net/inject' && object.spec.template.metadata.annotations[a] == 'enabled')"
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: |
          has(object.spec.template.metadata.annotations) &&
          object.spec.template.metadata.annotations.exists(
            a,
            a == "vault.k8s.corp.net/inject" &&
            object.spec.template.metadata.annotations[a] == "enabled"
          ) ?
          [
            has(object.spec.template.spec.volumes) ?
            JSONPatch{
              op: "add",
              path: "/spec/template/spec/volumes/-",
              value: [Object{
                  name: "vault-secret",
                  emptyDir: [Object{
                  medium: "memory"
                }],
              }]
            } : 
            JSONPatch{
              op: "add",
              path: "/spec/template/spec/-",
              value: [Object{
                  name: "vault-secret",
                  emptyDir: [Object{
                  medium: "memory"
                }],
              }]
            },
            has(object.spec.template.spec.containers[0].volumeMounts) ?
            JSONPatch{
              op: "add",
              path: "/spec/template/spec/containers/0/volumeMounts/-",
              value: [Object{
                  mountPath: "/secret",
                  name: "vault-secret"
              }]
            } : 
            JSONPatch{
              op: "add",
              path: "/spec/template/spec/containers/0/-",
              value: [Object{
                  mountPath: "/secret",
                  name: "vault-secret"
              }]
            }
          ] : []
