# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: E2E Tests

permissions: {}

on:
  pull_request:
    branches:
      - main
      - release-*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  argo-vpol:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [ v1.30.13, v1.31.9, v1.32.5, v1.33.1 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          k8s-version: ${{ matrix.k8s-version }}
      - name: Run Tests
        uses: ./.github/actions/run-tests
        with:
          path: argo-vpol

  karpenter-mpol:
          strategy:
            fail-fast: false
            matrix:
              k8s-version: [v1.30.13, v1.31.9, v1.32.5, v1.33.1]
          runs-on: ubuntu-latest
          steps:
          - name: Checkout
            uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
          - name: Setup Environment
            uses: ./.github/actions/setup-env
            with:
              k8s-version: ${{ matrix.k8s-version }}
          - name: Run Tests
            uses: ./.github/actions/run-tests
            with:
              path: karpenter-mpol

  best-practices-mpol:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.30.13, v1.31.9, v1.32.5, v1.33.1]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Environment
      uses: ./.github/actions/setup-env
      with:
        k8s-version: ${{ matrix.k8s-version }}
    - name: Run Tests
      uses: ./.github/actions/run-tests
      with:
        path: best-practices-mpol

  best-practices-gpol:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.30.13, v1.31.9, v1.32.5, v1.33.1]
        shard-index: [0,1]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Environment
      uses: ./.github/actions/setup-env
      with:
        k8s-version: ${{ matrix.k8s-version }}
    - name: Run Tests
      uses: ./.github/actions/run-tests
      with:
        path: best-practices-gpol
        shard-index: ${{ matrix.shard-index }}
        shard-count: 2

  best-practices-vpol:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.30.13, v1.31.9, v1.32.5, v1.33.1]
        shard-index: [0,1]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Environment
      uses: ./.github/actions/setup-env
      with:
        k8s-version: ${{ matrix.k8s-version }}
    - name: Run Tests
      uses: ./.github/actions/run-tests
      with:
        path: best-practices-vpol
        shard-index: ${{ matrix.shard-index }}
        shard-count: 2

  castai-mpol:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.30.13, v1.31.9, v1.32.5, v1.33.1]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Environment
      uses: ./.github/actions/setup-env
      with:
        k8s-version: ${{ matrix.k8s-version }}
    - name: Run Tests
      uses: ./.github/actions/run-tests
      with:
        path: castai-mpol

  cleanup-dpol:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.30.13, v1.31.9, v1.32.5, v1.33.1]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Environment
      uses: ./.github/actions/setup-env
      with:
        k8s-version: ${{ matrix.k8s-version }}
    - name: Run Tests
      uses: ./.github/actions/run-tests
      with:
        path: cleanup-dpol

  istio-mpol:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.30.13, v1.31.9, v1.32.5, v1.33.1]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Environment
      uses: ./.github/actions/setup-env
      with:
        k8s-version: ${{ matrix.k8s-version }}
    - name: Run Tests
      uses: ./.github/actions/run-tests
      with:
        path: istio-mpol

  kubecost-mpol:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.30.13, v1.31.9, v1.32.5, v1.33.1]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Environment
      uses: ./.github/actions/setup-env
      with:
        k8s-version: ${{ matrix.k8s-version }}
    - name: Run Tests
      uses: ./.github/actions/run-tests
      with:
        path: kubecost-mpol

  kubevirt-gpol:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.30.13, v1.31.9, v1.32.5, v1.33.1]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Environment
      uses: ./.github/actions/setup-env
      with:
        k8s-version: ${{ matrix.k8s-version }}
    - name: Run Tests
      uses: ./.github/actions/run-tests
      with:
        path: kubevirt-gpol

  linkerd-mpol:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.30.13, v1.31.9, v1.32.5, v1.33.1]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Environment
      uses: ./.github/actions/setup-env
      with:
        k8s-version: ${{ matrix.k8s-version }}
    - name: Run Tests
      uses: ./.github/actions/run-tests
      with:
        path: linkerd-mpol

  other:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.30.13, v1.31.9, v1.32.5, v1.33.1]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Environment
      uses: ./.github/actions/setup-env
      with:
        k8s-version: ${{ matrix.k8s-version }}
    - name: Run Tests
      uses: ./.github/actions/run-tests
      with:
        path: other

  other-vpol:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.30.13, v1.31.9, v1.32.5, v1.33.1]
        shard-index: [0,1,2,3,4,5,6,7,8]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Environment
      uses: ./.github/actions/setup-env
      with:
        k8s-version: ${{ matrix.k8s-version }}
    - name: Run Tests
      uses: ./.github/actions/run-tests
      with:
        path: other-vpol
        shard-index: ${{ matrix.shard-index }}
        shard-count: 9

  other-mpol:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.30.13, v1.31.9, v1.32.5, v1.33.1]
        shard-index: [0,1,2,3,4,5,6,7,8]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Environment
      uses: ./.github/actions/setup-env
      with:
        k8s-version: ${{ matrix.k8s-version }}
    - name: Run Tests
      uses: ./.github/actions/run-tests
      with:
        path: other-mpol
        shard-index: ${{ matrix.shard-index }}
        shard-count: 9

  other-gpol:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.30.13, v1.31.9, v1.32.5, v1.33.1]
        shard-index: [0,1,2,3,4,5,6,7,8]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Environment
      uses: ./.github/actions/setup-env
      with:
        k8s-version: ${{ matrix.k8s-version }}
    - name: Run Tests
      uses: ./.github/actions/run-tests
      with:
        path: other-gpol
        shard-index: ${{ matrix.shard-index }}
        shard-count: 9

  other-ivpol:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.30.13, v1.31.9, v1.32.5, v1.33.1]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Environment
      uses: ./.github/actions/setup-env
      with:
        k8s-version: ${{ matrix.k8s-version }}
    - name: Run Tests
      uses: ./.github/actions/run-tests
      with:
        path: other-ivpol

  pod-security-vpol:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.30.13, v1.31.9, v1.32.5, v1.33.1]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Environment
      uses: ./.github/actions/setup-env
      with:
        k8s-version: ${{ matrix.k8s-version }}
    - name: Run Tests
      uses: ./.github/actions/run-tests
      with:
        path: pod-security-vpol

  psa-mpol:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.30.13, v1.31.9, v1.32.5, v1.33.1]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Environment
      uses: ./.github/actions/setup-env
      with:
        k8s-version: ${{ matrix.k8s-version }}
    - name: Run Tests
      uses: ./.github/actions/run-tests
      with:
        path: psa-mpol

  psp-migration-mpol:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.30.13, v1.31.9, v1.32.5, v1.33.1]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Environment
      uses: ./.github/actions/setup-env
      with:
        k8s-version: ${{ matrix.k8s-version }}
    - name: Run Tests
      uses: ./.github/actions/run-tests
      with:
        path: psp-migration-mpol

  velero-mpol:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.30.13, v1.31.9, v1.32.5, v1.33.1]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Environment
      uses: ./.github/actions/setup-env
      with:
        k8s-version: ${{ matrix.k8s-version }}
    - name: Run Tests
      uses: ./.github/actions/run-tests
      with:
        path: velero-mpol

  e2e-required-success:
    name: e2e-required
    needs:
    - argo-vpol
    - karpenter-mpol
    - best-practices-mpol
    - best-practices-gpol
    - best-practices-vpol
    - castai-mpol
    - cleanup-dpol
    - istio-mpol
    - kubecost-mpol
    - kubevirt-gpol
    - linkerd-mpol
    - other
    - other-vpol
    - other-mpol
    - other-gpol
    - other-ivpol
    - pod-security-vpol
    - psa-mpol
    - psp-migration-mpol
    - velero-mpol
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
    - run: ${{ true }}

  e2e-required-failure:
    name: e2e-required
    needs:
    - argo-vpol
    - karpenter-mpol
    - best-practices-mpol
    - best-practices-gpol
    - best-practices-vpol
    - castai-mpol
    - cleanup-dpol
    - istio-mpol
    - kubecost-mpol
    - kubevirt-gpol
    - linkerd-mpol
    - other
    - other-vpol
    - other-mpol
    - other-gpol
    - other-ivpol
    - pod-security-vpol
    - psa-mpol
    - psp-migration-mpol
    - velero-mpol
    runs-on: ubuntu-latest
    if: ${{ failure() || cancelled() }}
    steps:
    - run: ${{ false }}
